name: "Set up database"
description: "Create db and run migrations"
runs:
  using: "composite"
  steps:
    - name: Setup test database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://complaint_tracker:postgres@localhost:5432/complaint_tracker_test
      run: |
        bundle exec rake db:create db:migrate
