name: "Set up javascript"
description: "Set up javascript and yarn dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.0'
        cache: 'yarn'

    - name: Install yarn dependencies
      shell: bash
      run: yarn install --frozen-lockfile
