name: "Set up database"
description: "Create db and run migrations"
inputs:
  rails_env:
    description: RAILS_ENV to set. Defaults to test
    required: false
    default: test
  database_url:
    description: DATABASE_URL to set
    required: false
    default: postgres://complaint_tracker:postgres@localhost:5432/complaint_tracker_test
runs:
  using: "composite"
  steps:
    - name: Create database
      env:
        RAILS_ENV: ${{ inputs.rails_env }}
        DATABASE_URL: ${{ inputs.database_url }}
      shell: bash
      run: bundle exec rake db:create

    - name: Migrate database
      env:
        RAILS_ENV: ${{ inputs.rails_env }}
        DATABASE_URL: ${{ inputs.database_url }}
      shell: bash
      run: bundle exec rake db:migrate
