name: "Set up database"
description: "Create db and run migrations"
runs:
  using: "composite"
  steps:
    - name: Create test database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://complaint_tracker:postgres@localhost:5432/complaint_tracker_test
      shell: bash
      run: bundle exec rake db:create

    - name: Migrate test database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://complaint_tracker:postgres@localhost:5432/complaint_tracker_test
      shell: bash
      run: bundle exec rake db:migrate
