name: "Set up project"
description: "Set up project and dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # bundler-cache automatically installs gems
        bundler-cache: true
        cache-version: 1
